apiVersion: v1
kind: Service
metadata:
  name: hello-world-api
  namespace: hello
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: hello-world-api
